export const projects = [
  {
    title: 'Bookmark',
    description: "Using React, Next, TailwindCSS & Firebase - from start to finish. The App is called Bookmark and it is a simple browser extension.",
    image: '/images/bookmark.webp',
    tags: ['React', 'Next', 'Firebase', 'TailwindCSS'],
    visit: 'https://github.com/yusuf591-cpu/Bookmark',
    source: 'https://bookmark-dusky.vercel.app/',
    id: 0,
  },
  {
    title: 'Shantui',
    description: "Компания СП ООО 'SPETS TEXNIKA TASHKENT' (Спецтехника Ташкент) - имеет 17 летний опыт в сфере поставок спецтехники и оборудования из Китая.",
    image: '/images/shantui.webp',
    tags: ['React', 'Next', 'Bootstrap', "Python", "Django"],
    visit: 'https://github.com/yusuf591-cpu',
    source: 'https://shantuiuzb.com',
    id: 1,
  },
  {
    title: 'Sgtshop',
    description: "E-commerce site to buying tecnical equipment. The site is built with React, Redux, Bootstrap, Django.",
    image: '/images/Sgtshop.webp',
    tags: ["Reactjs", "Redux", "Bootstrap"],
    visit: 'https://github.com/yusuf591-cpu',
    source: 'https://www.sgtshop.uz/',
    id: 2,
  },
  {
    title: 'Moviekey',
    description: "Moviekey is a movie search engine. It is a simple web application that allows users to get information about them.",
    image: '/images/moviekey.webp',
    tags: ['React', 'Nextjs', "TailwindCSS", "TMDB"],
    visit: 'https://github.com/yusuf591-cpu/MovieKey',
    source: 'https://movie-key.vercel.app/',
    id: 3,
  },
  {
    title: 'Manage',
    description: "Manage makes it simple for software teams to plan day-to-day tasks while keeping the larger team goals in view.",
    image: '/images/manage.webp',
    tags: ["TailwindCSS"],
    visit: 'https://github.com/yusuf591-cpu/Manage_tailwind/',
    source: 'https://yusuf-saydullayev.github.io/Manage_tailwind/',
    id: 4,
  },
  {
    title: 'Notes',
    description: "A PASSIONATE WEB COMPANY",
    image: '/images/Notes.webp',
    tags: ["React", "Bootstrap", "Owl Carousel"],
    visit: 'https://github.com/yusuf591-cpu/notes-web',
    source: 'https://notes-com.netlify.app/',
    id: 5,
  },
  {
    title: 'Astro Example',
    description: "Simple News app,  using Astro",
    image: '/images/Astro.webp',
    tags: ["Astro","TailwindCSS", "News API"],
    visit: 'https://github.com/yusuf591-cpu/Astro',
    source: 'https://astro-poux.netlify.app',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2019, text: 'Learned Web development at the educational center PROWEB', },
  { year: 2020, text: 'Learned React', },
  { year: 2021, text: 'Frontend Developer RedFox Agency' },
  { year: 2022, text: 'Frontend Developer West Coast and Choy Media' },
];
